baseURL = "https://soldes.tole.es"
title = "Soldes pour vôtre famile!"
theme = "portfolio"
languageCode = "es-es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
paginate = 20

[sitemap]
  changefreq = "hourly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Soldes pour vôtre famile!"
  copyright = ""
  sidebarAbout = []
  # Enable Google Analytics by entering your tracking code
  gtag = "G-B78Y62XVYL"
  yandex = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Raíz  "
  url = "/"
  home = true


  [outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]
